using System.Diagnostics;
using Azoth.Tools.Bootstrap.Compiler.Core;
using Azoth.Tools.Bootstrap.Compiler.CST;
using Azoth.Tools.Bootstrap.Compiler.Tokens;
using Azoth.Tools.Bootstrap.Compiler.Types;

namespace Azoth.Tools.Bootstrap.Compiler.Semantics.Basic.ImplicitOperations
{
    /// <summary>
    /// The implicit conversions do not have "Syntax" in their name, because
    /// there is no corresponding syntax. They are never generated by the parser,
    /// but are inserted during type checking.
    /// </summary>
    internal abstract class ImplicitConversionExpression : ImplicitExpressionSyntax, IImplicitConversionExpressionSyntax
    {
        public IExpressionSyntax Expression { [DebuggerHidden] get; }
        DataType IImplicitConversionExpressionSyntax.DataType { [DebuggerHidden] get => DataType!; }

        protected ImplicitConversionExpression(
            TextSpan span,
            DataType convertToType,
            IExpressionSyntax expression,
            ExpressionSemantics semantics)
            : base(convertToType, span, semantics)
        {
            Expression = expression;
        }

        public abstract override string ToString();

        public string ToGroupedString(OperatorPrecedence surroundingPrecedence)
        {
            return ToString();
        }
    }
}
